name: Bitcoin Advance CI/CD (Docker)

on:
  push:
    branches: [ "main" ]

jobs:
  build-train-deploy:
    runs-on: ubuntu-latest
    steps:
    # 1. Jupuk Kodingan
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Setup Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # 3. Install Alat Perang (VERSI STABIL 2.14.1)
    - name: Install dependencies
      run: |
        # KITA KUNCI NENG VERSI 2.14.1 BEN ORA ERROR JAVA
        pip install "mlflow==2.14.1" dagshub pandas scikit-learn numpy matplotlib seaborn virtualenv

    # 4. TRAINING MODEL
    - name: Train Model
      env:
        DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      run: |
        cd MLProject
        python modelling.py

    # 5. LOGIN DOCKER HUB
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 6. BUILD & PUSH DOCKER IMAGE
    - name: Build and Push Docker Image
      env:
        MLFLOW_TRACKING_URI: "https://dagshub.com/RandraFerdian/Eksperimen_SML_Randra.mlflow"
        DAGSHUB_USER_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      run: |
        echo "üîç Nggoleki Run ID paling anyar..."
        LATEST_RUN=$(python -c "import mlflow; mlflow.set_tracking_uri('$MLFLOW_TRACKING_URI'); runs = mlflow.search_runs(experiment_names=['Bitcoin_Final_RF']); print(runs.iloc[0].run_id)")
        
        echo "‚úÖ Nemu Run ID: $LATEST_RUN"
        
        # --- PASTIKE USERNAME IKI BENER ---
        DOCKER_USER="randraferdian"
        IMAGE_NAME="bitcoin-sniper"
        
        echo "üê≥ Mulai Mbangun Docker Image..."
        
        # Printah Build (Versi 2.14.1 luwih nurut)
        mlflow models build-docker \
          -m "runs:/$LATEST_RUN/best_random_forest_final" \
          -n "docker.io/$DOCKER_USER/$IMAGE_NAME:latest"

        echo "üöÄ Nge-Push menyang Docker Hub..."
        docker push "docker.io/$DOCKER_USER/$IMAGE_NAME:latest"